 #/* 
 #* Virtue: better than VICE
 #* File: makefile
 #* Usage: A simple makefile. Run `make` in terminal to compile.
 #*/
 all:
	gcc -ggdb2 xboard.c virtue.c uci.c evaluate.c pvtable.c init.c bitboards.c hashkeys.c board.c data.c attack.c io.c movegen.c validate.c makemove.c perft.c search.c misc.c polybook.c polykeys.c fen.c -o virtue